[PHP]
extension_dir="C:\laragon\bin\php\php-8.3.16-Win32-vs16-x64\ext"
extension=openssl
extension=curl
extension=mbstring
extension=fileinfo
extension=pdo_sqlite
extension=sqlite3
extension=intl
extension=zip

memory_limit=512M
upload_max_filesize=12M
post_max_size=120M
max_file_uploads=50
date.timezone=Africa/Lagos
