<div class="row justify-content-center"><div class="col-xl-10"><div class="form-panel">
  @if(session('success') === 'master')<div class="alert alert-success">Votre candidature en Master a bien été enregistrée.</div>@endif
  <form method="POST" action="{{ route('master.store') }}" enctype="multipart/form-data" class="needs-validation">@csrf
    <h3 class="h5 mb-3">Identité et coordonnées</h3><div class="row g-3"><div class="col-md-6"><label class="form-label">Nom</label><input class="form-control" name="nom" value="{{ old('nom') }}" required></div><div class="col-md-6"><label class="form-label">Prénom</label><input class="form-control" name="prenom" value="{{ old('prenom') }}" required></div><div class="col-md-4"><label class="form-label">Date de naissance</label><input class="form-control" type="date" name="date_naissance" value="{{ old('date_naissance') }}" required></div><div class="col-md-4"><label class="form-label">Nationalité</label><input class="form-control" name="nationalite" value="{{ old('nationalite') }}" required></div><div class="col-md-4"><label class="form-label">Résidence</label><input class="form-control" name="residence" value="{{ old('residence') }}" required></div><div class="col-md-6"><label class="form-label">Téléphone</label><input class="form-control" name="telephone" value="{{ old('telephone') }}" required></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" type="email" name="email" value="{{ old('email') }}" required></div></div>
    <h3 class="h5 mt-4 mb-3">Parcours et projet</h3><div class="row g-3"><div class="col-md-6"><label class="form-label">Spécialité demandée</label><input class="form-control" name="specialite" value="{{ old('specialite') }}" required></div><div class="col-md-6"><label class="form-label">Niveau demandé</label><select class="form-select" name="niveau" required><option value="Master 1">Master 1</option><option value="Master 2">Master 2</option></select></div><div class="col-md-6"><label class="form-label">Dernier diplôme</label><input class="form-control" name="dernier_diplome" value="{{ old('dernier_diplome') }}" required></div><div class="col-md-6"><label class="form-label">Établissement</label><input class="form-control" name="etablissement" value="{{ old('etablissement') }}" required></div><div class="col-md-4"><label class="form-label">Année d’obtention</label><input class="form-control" type="number" name="annee_obtention" min="1990" max="2030" value="{{ old('annee_obtention') }}" required></div><div class="col-md-4"><label class="form-label">Mention</label><input class="form-control" name="mention" value="{{ old('mention') }}"></div><div class="col-md-4"><label class="form-label">Moyenne /20</label><input class="form-control" type="number" step=".01" min="0" max="20" name="moyenne" value="{{ old('moyenne') }}"></div><div class="col-12"><label class="form-label">Projet professionnel</label><textarea class="form-control" name="projet_professionnel" rows="6" minlength="100" required>{{ old('projet_professionnel') }}</textarea></div></div>
    <h3 class="h5 mt-4 mb-3">Pièces du dossier</h3><div class="row g-3">@foreach(['diplome'=>'Diplôme','releves_notes[]'=>'Relevés de notes','cv'=>'CV au format PDF','lettre_motivation'=>'Lettre de motivation PDF','piece_identite'=>'Pièce d’identité'] as $field => $label)<div class="col-md-6"><label class="form-label">{{ $label }}</label><input class="form-control" type="file" name="{{ $field }}" {{ str_contains($field, 'releves') ? 'multiple' : '' }} required></div>@endforeach<div class="col-md-6"><label class="form-label">Autres documents</label><input class="form-control" type="file" name="autres_documents[]" multiple></div></div>
    <div class="form-check mt-4"><input class="form-check-input" type="checkbox" name="declaration" value="1" id="master-declaration" required><label class="form-check-label" for="master-declaration">Je certifie l’exactitude des informations fournies.</label></div><div class="form-check mt-2"><input class="form-check-input" type="checkbox" name="consentement" value="1" id="master-consent" required><label class="form-check-label" for="master-consent">J’autorise le traitement de mes données pour cette candidature.</label></div>
    <button class="btn btn-insg-primary mt-4" type="submit"><i class="bi bi-send me-2"></i>Envoyer ma candidature</button>
  </form>
</div></div></div>
