@extends('contests.layout')
@section('title','Candidature — '.$contest->title)
@section('content')
<section class="page-hero"><div class="container"><span class="eyebrow text-white">{{ $contest->reference }}</span><h1>{{ $contest->title }}</h1><p>Candidature en ligne — {{ $contest->academic_year }}</p></div></section><section class="section"><div class="container"><form method="POST" enctype="multipart/form-data" action="{{ route('contests.store',$contest) }}" class="form-panel mx-auto" style="max-width:1050px">@csrf
@if($errors->any())<div class="alert alert-danger"><strong>Veuillez corriger le formulaire.</strong><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<h2 class="h5 mb-3">Identité</h2><div class="row g-3"><div class="col-md-4"><label class="form-label">Nom</label><input class="form-control" name="last_name" value="{{ old('last_name') }}" required></div><div class="col-md-8"><label class="form-label">Prénom(s)</label><input class="form-control" name="first_names" value="{{ old('first_names') }}" required></div><div class="col-md-3"><label class="form-label">Sexe</label><select class="form-select" name="gender" required><option value="">Choisir</option><option value="F">Féminin</option><option value="M">Masculin</option></select></div><div class="col-md-3"><label class="form-label">Date de naissance</label><input type="date" class="form-control" name="birth_date" value="{{ old('birth_date') }}" required></div><div class="col-md-3"><label class="form-label">Lieu de naissance</label><input class="form-control" name="birth_place" value="{{ old('birth_place') }}" required></div><div class="col-md-3"><label class="form-label">Nationalité</label><input class="form-control" name="nationality" value="{{ old('nationality','Gabonaise') }}" required></div></div>
<h2 class="h5 mt-4 mb-3">Coordonnées</h2><div class="row g-3"><div class="col-md-6"><label class="form-label">Email</label><input type="email" class="form-control" name="email" value="{{ old('email') }}" required></div><div class="col-md-6"><label class="form-label">Téléphone</label><input class="form-control" name="phone" value="{{ old('phone') }}" required></div><div class="col-md-6"><label class="form-label">Adresse</label><input class="form-control" name="address" value="{{ old('address') }}"></div><div class="col-md-3"><label class="form-label">Ville</label><input class="form-control" name="city" value="{{ old('city','Libreville') }}" required></div><div class="col-md-3"><label class="form-label">Province</label><input class="form-control" name="province" value="{{ old('province') }}"></div></div>
<h2 class="h5 mt-4 mb-3">Parcours académique</h2><div class="row g-3"><div class="col-md-4"><label class="form-label">Niveau d’étude</label><input class="form-control" name="study_level" value="{{ old('study_level') }}" required></div><div class="col-md-4"><label class="form-label">Diplôme</label><input class="form-control" name="diploma" value="{{ old('diploma') }}" required></div><div class="col-md-4"><label class="form-label">Année d’obtention</label><input type="number" class="form-control" name="graduation_year" value="{{ old('graduation_year') }}"></div><div class="col-md-6"><label class="form-label">Établissement d’origine</label><input class="form-control" name="previous_school" value="{{ old('previous_school') }}"></div><div class="col-md-3"><label class="form-label">Série / filière</label><input class="form-control" name="field" value="{{ old('field') }}"></div><div class="col-md-3"><label class="form-label">Spécialité</label><input class="form-control" name="specialty" value="{{ old('specialty') }}"></div><div class="col-12"><label class="form-label">Pièces justificatives</label><input type="file" class="form-control" name="documents[]" accept=".pdf,.jpg,.jpeg,.png" multiple required><div class="form-text">PDF, JPG ou PNG — 10 Mo maximum par fichier.</div></div><div class="col-12"><label class="form-check"><input class="form-check-input" type="checkbox" name="consent" value="1" required><span class="form-check-label">Je certifie l’exactitude des informations et autorise leur traitement pour ce concours.</span></label></div></div><button class="btn btn-insg-primary btn-lg mt-4" type="submit"><i class="bi bi-send me-2"></i>Envoyer ma candidature</button></form></div></section>
@endsection
